spring :
  application :
    name : fz-matching-service
  datasource:
    url : jdbc:mysql://localhost:3306/frenzo_prod
    username : appuser
    password : Frrenzo2026$
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa :
    hibernate :
      ddl-auto : none
    show-sql : true

server :
  port : 9091

eureka :
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    preferIpAddress : true

info:
  app:
   name: matching
   description: matching-service
   version: 0.0.1

management:
  endpoints:
     web:
       exposure:
         include: "*"
  info:
     env:
       enabled: true

token:
  access:
    expiration: 2_592_000
  refresh:
    expiration: 31_536_000
  secret:
     key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855