package tech.grastone.fz.matching.enums;

public enum Lifestyle {
    NONE, PET_LOVER, FITNESS, VEGAN, NIGHT_OWL, EARLY_BIRD, BOOKWORM, GAMER,
    ADVENTURE_SEEKER, TECHY, CREATIVE_ARTS, MUSIC_LOVER, PUZZLE_LOVER
}