package tech.grastone.fz.matching.enums;

public enum LimitType {
	PROFILE_VIEW, REQUEST_SENT, CONNECTION_ACCEPTED, VIBE_PROFILE_ACTION, VIBE_JOIN, SEEN_YOU_VIEW,
	REWARDED_VIBE_PROFILE_ACTION, REWARDED_VIBE_JOIN, REWARDED_SEEN_YOU_VIEW
}
